### ISSUE TITLE
Cannot install to ComfyUI

### ISSUE THREAD

**Issue by bluesky61** [coreyryanhanson/ComfyQR-scanning-nodes#1]
Im not sure but this is error message when ComfyUI starts:

Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\zbar_library.py", line 58, in load
    dependencies, libzbar = load_objects(Path(''))
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\zbar_library.py", line 50, in load_objects
    deps = [
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\zbar_library.py", line 51, in <listcomp>
    cdll.LoadLibrary(str(directory.joinpath(dep)))
  File "ctypes\__init__.py", line 452, in LoadLibrary
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'libiconv.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR-scanning-nodes\__init__.py", line 1, in <module>
    from .qr_validation import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR-scanning-nodes\qr_validation.py", line 3, in <module>
    from pyzbar.pyzbar import decode
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\wrapper.py", line 151, in <module>
    zbar_version = zbar_function(
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\wrapper.py", line 148, in zbar_function
    return prototype((fname, load_libzbar()))
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\wrapper.py", line 127, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\zbar_library.py", line 60, in load
    dependencies, libzbar = load_objects(Path(__file__).parent)
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\zbar_library.py", line 54, in load_objects
    libzbar = cdll.LoadLibrary(str(directory.joinpath(fname)))
  File "ctypes\__init__.py", line 452, in LoadLibrary
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\libzbar-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

Cannot import C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR-scanning-nodes module for custom nodes: Could not find module 'C:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\pyzbar\libzbar-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by coreyryanhanson** [comment]
@bluesky61 It looks like pyzbar (the qr code python library) is missing dependencies on your system. Unfortunately I don't have a Windows machine to test on, but based on a search I suspect this would be the correct path to solve it (Make sure you have libiconv.dll in the right location). https://stackoverflow.com/questions/64570443/q-how-to-fix-the-missing-dependancies-in-pyzbar
If you figure it out, please give an update on what you did to fix it. There will likely be other Windows users that run into the same problem.

**Comment by Brotoshi** [comment]
Hey pals! Unfortunately I'm also catching a similar error  using Google Colab (pro) - 
	"Success is not about being better than someone else. It's about being better than you used to be." - Unknown

Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyQR/__init__.py", line 1, in <module>
    from .qr_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyQR/qr_nodes.py", line 2, in <module>
    import qrcode
ModuleNotFoundError: No module named 'qrcode'

Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyQR module for custom nodes: No module named 'qrcode'
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyQR-scanning-nodes/__init__.py", line 1, in <module>
    from .qr_validation import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyQR-scanning-nodes/qr_validation.py", line 3, in <module>
    from pyzbar.pyzbar import decode
ModuleNotFoundError: No module named 'pyzbar'

Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyQR-scanning-nodes module for custom nodes: No module named 'pyzbar'
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.


Import times for custom nodes:
   1.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/Mile_High_Styler
   1.9 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/IPAdapter-ComfyUI
--->    2.1 seconds (IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyQR-scanning-nodes
   2.2 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/stability-ComfyUI-nodes
--->   2.2 seconds (IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyQR
   4.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   4.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   5.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/was-node-suite-comfyui
   5.2 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   5.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   5.7 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
  20.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux
  35.5 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager
  42.7 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
  59.3 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes

best of luck to anyone trying to figure it out, wish i could help !

**Comment by coreyryanhanson** [comment]
@Brotoshi Fixing your error is much more straightforward.

You are missing dependencies for this repo (and the other one). From what I understand, ComfyUI manager should automatically install the python dependencies in the requirements.txt file. For some reason the qrcode and pyzbar libraries are missing on yours. You can solve that by going into the virtual environment that you have ComfyUI installed and entering the command
```bash
pip install qrcode pyzbar
```
Or if that method is unavailable you should still be able to install those dependencies within the notebook by running a cell first with:
```
!pip install qrcode pyzbar
```
For this repo, there's also the matter of requiring the underlying zbar libraries. Try also running this command for that:
```
!sudo apt-get install libzbar0
```
If that doesn't work, take out the sudo and enter in a cell `!apt-get install libzbar0` . I'm not as confident as that last part working in collab because its success is highly dependent on the permissions for installing packages there. I've never attempted to install system packages within a notebook, so it may not work.

Hope that helps!

**Comment by Brotoshi** [comment]
Hey @coreyryanhanson, thank you! sorry didn't have a chance to respond earlier but very much appreciated. That just about worked like a charm; I ran the first [pip install qrcode pyzbar] yesterday to no avail, but combined with the [ !sudo apt-get install libzbar0 ] got it all sorted - however the issue I'm trouble shooting now is the [ pipeLoader - Node Version Mismatch ] - searched for pipeloader by double clicking the plot and see that i have two versions named "ttN PipeLoader" & "ttn...XL" , tried to swap and plugging  in to those ones but Negative. - SIDE NOTE* much enjoyed the article read on Medium as its the only one with sdxl compatibility that i've found, looking forward to playing with the workflow and will for sure be buying you a coffee or two! gracias encore.

**Comment by coreyryanhanson** [comment]
@Brotoshi The pipeLoader class isn't a part of this repo, but I did a search and it looks like it is being caused by the tinyterraNodes project. It looks like others are experiencing your problem as well. https://github.com/TinyTerra/ComfyUI_tinyterraNodes/issues/61

Also I should give you a heads up. For QR ControlNets specifically, XL compatibility still hasn't arrived. I've been eagerly waiting myself and feel like it should be any day now. If I had to guess, the first one will most likely come out from a new version of QR code monster by @pop123123123. It appears he has been working on it but there have been some issues slowing down the release https://civitai.com/models/111006/qr-code-monster?commentId=248094&modal=commentThread
Until then, I'd recommend using a 1.5 model with 768 x 768 output.

Hope this helps. And appreciate the coffee offer! I would need to get that set up on my pages first. I know I probably should, but I've been putting it off haha :)

**Comment by Brotoshi** [comment]
ah my bad ! I thought your flow was using SDXL, none the less I'm pumped to give your template a go, I've been using QRmonster on auto1111 for a while now and only just moved to comfy in the last week cause I've had it with all the presets needed to manage the CN-QR workflow with auto11,  so I'm on that ComfyPill now :) - thanks again for the link up top! will post results when i'm up and good!

**Comment by DawgZter** [comment]
@coreyryanhanson QRCode Monster for SDXL is out! https://huggingface.co/monster-labs/control_v1p_sdxl_qrcode_monster
